language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="1bf7ef0c-7301-4f23-bd38-497b6c4949e7"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - the.tylertyler@gmail.com
    on_success: never # default: change
    on_failure: always # default: always